### ISSUE TITLE
Unhandled Exception when use_deferred_loading: false

### ISSUE THREAD

**Issue by Comanx** [Innim/flutter_multiple_localization#10]
my app and plugin pubspec.yaml
```
......
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  use_deferred_loading: false
```
```
E/flutter (17277): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:multiple_localization/src/multiple_localization.dart': Failed assertion: line 50 pos 12: 'intl_private.messageLookup is intl_private.UninitializedLocaleData': is not true.
E/flutter (17277): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (17277): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (17277): #2      MultipleLocalizations._init (package:multiple_localization/src/multiple_localization.dart:50:12)
E/flutter (17277): #3      MultipleLocalizations.load (package:multiple_localization/src/multiple_localization.dart:78:32)
E/flutter (17277): #4      _AppLocalizationsDelegate.load (package:srtk/l10n/srtk_i10n.dart:15:34)
E/flutter (17277): #5      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
E/flutter (17277): #6      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:558:62)
E/flutter (17277): #7      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:520:5)
E/flutter (17277): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5101:55)
......
```
plugin _AppLocalizationsDelegate class
```
class _AppLocalizationsDelegate extends LocalizationsDelegate<S> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'zh', 'it', 'de'].contains(locale.languageCode);

  @override
  Future<S> load(Locale locale) {
    return MultipleLocalizations.load(initializeMessages, locale, (l) => S.load(locale), setDefaultLocale: true);
  }

  @override
  bool shouldReload(LocalizationsDelegate<S> old) => false;
}

/// Srtk localization.
class SrtkLocalizations {
  /// Delegate.
  static const LocalizationsDelegate<S> delegate = _AppLocalizationsDelegate();

  static SrtkLocalizations of(BuildContext context) => Localizations.of<SrtkLocalizations>(context, SrtkLocalizations)!;
}
```

**Comment by rs-huannd1** [comment]
I also got the same error as this
I use:
  multiple_localization: 0.4.0
  intl: 0.18.1

**Comment by rs-huannd1** [comment]
I fixed it. @Comanx 
my code: 
import 'package:..._app/l10n/l10n.dart';
import 'package:..._common_app/l10n/l10n.dart' as l10_common;
....
L10n.delegate,
l10_common.L10n.delegate,
